language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - pytest --cov-report term --cov=comptox_ai tests/
after_success:
  # Ignore coveralls failures as the coveralls server is not very reliable
  # but we don't want travis to report a failure in the github UI just
  # because the coverage report failed to be published.
  - coveralls
