language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - pytest --cov-report term --cov=comptox_ai tests/
services:
  - neo4j
after_success:
  - codecov