language: python
dist: trusty
python:
  - "3.7"
services:
  - neo4j
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - pytest --cov-report term --cov=comptox_ai tests/
after_script:
  - codecov