language: python
dist: trusty
python:
  - "3.7"
before_install:
  - wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add -
  - echo 'deb https://debian.neo4j.com stable latest' | sudo tee -a /etc/apt/sources.list.d/neo4j.list
  - sudo apt-get update
  - sudo apt-get install neo4j=1:3.5.14
services:
  - neo4j
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - pytest --cov-report term --cov=comptox_ai tests/
after_script:
  - codecov