---
# Default configuration for ComptoxAI
neo4j:
  username: neo4j
  password: neo4j
  hostname: localhost
  protocol: bolt
  port: 7687

mongodb:
  username: 
  password:
  hostname: 127.0.0.1
  port: 27017

data:
  prefix: D:\data\
  tempdir: D:\data\comptox_ai\

...