# To use:
#
#   $ conda env create -f environment.yml
#   $ conda activate comptox_ai

name: comptox_ai
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - nodejs=16.6.1
  - ablog=0.10.19
  - numpy=1.21.2
  - scipy=1.7.1
  - pandas=1.3.3
  - mysqlclient=2.0.3
  - neo4j-python-driver=4.3.4
  - networkx=2.6.3
  - py2neo=2021.1.5
  - rdflib=5.0.0
  - openpyxl=3.0.8
  - owlready2=0.34
  - pyyaml=5.4.1