[[redirects]]
  from = "/api/docs/"
  to = "http://3.235.225.44:3000/docs"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
  
[[redirects]]
  from = "/api"
  to = "http://3.235.225.44:3000/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
