---
# Automates deploy of comptox_ai doc page to AWS on GitHub release
name: cd-release-doc

# Deployed on release or on workflow dispatch
on:
  release:
    types:
      - created
  workflow_dispatch:

# Define the jobs in the workflow
jobs:
  release-doc:
    runs-on: ubuntu-latest

    steps:
      # Step: Check out the repository's code to the runner
      - name: checkout-code
        uses: actions/checkout@v2

      # Step: Configure AWS credentials from AWS role
      - name: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::146408842325:role/comptox_ai
          aws-region: us-east-1

      # Step: Run deploy script on the EC2 instance
      - name: deploy-to-ec2
        run: |
          rsync -avz --no-times \
          ./docs/build/html/. \
          ec2-user@54.92.148.244:/usr/share/nginx/html/
