---
name: ci-python-test

# Define the events that trigger the workflow
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

# Define the jobs in the workflow
jobs:
  python-test:
    # Define the type of runner to use
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    # # Define strategy for matrix builds
    # strategy:
    #   matrix:
    #     # You can change the default value as needed
    #     python-version: ['3.8', '3.9', '3.10']

    steps:
      # Step: Check out the repository's code to the runner
      - name: checkout-code
        uses: actions/checkout@v3

      # # Step: Set up Python environment
      # - name: setup-python-env ${{ matrix.python-version }}
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: ${{ matrix.python-version }}

      # Step: Install project dependencies using pip
      - name: install-dependencies
        # run: |
        #   python -m pip install --upgrade pip setuptools wheel
        #   python -m pip install .
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: comptox_ai
          environment-file: environment.yml
          python-version: 3.9
          auto-activate-base: false
        

      # Step: List installed packages
      - name: list-packages
      #   run: pip list
        run: |
            source $(conda info --base)/etc/profile.d/conda.sh
            conda info
            conda list

      # Step: Run tests with Pytest
      - name: run-tests
        run: |
            source $(conda info --base)/etc/profile.d/conda.sh
            python -m pytest
