# This is a basic workflow to help you get started with Actions

name: Deploy ComptoxAI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ deploy ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: [self-hosted, linux]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build docs
        working-directory: ./docs
        run: |
          conda activate comptox_ai
          make html
        
      - name: Build app
        working-directory: ./web/packages/app
        run: |
          npm ci
          cp ./build/static/js/* ../../../docs/build/html/_static/js/
          
      - name: Build web API
        working-directory: ./web/packages/api
        run: |
          npm ci
          pm2 restart api-app
