name: Documentation build

on:
    - push
    - workflow_dispatch
    - pull_request

jobs:
    build-docs:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.8', '3.9', '3.10']

        steps:
            - uses: actions/checkout@v3
            - name: Build document
              uses: andreasofthings/doc-build@v13
              with:
                  docs: 'docs'
                  dest: 'build'
