name: Python/Database CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    
    services:
      neo4j:
        image: neo4j:4.2.5
        env:
          NEO4JLABS_PLUGINS: '["graph-data-science"]'
          NEO4J_AUTH: neo4j/${{ secrets.NEO4J_PASSWORD }}
          NEO4J_dbms_connector_bolt_advertised__address: localhost:7687
        ports:
          - 7687:7687

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      - name: setup conda
        uses: s-weigand/setup-conda@v1.0.5
        with:
          activate-conda: true
          python-version: 3.7.5
          conda-channels: anaconda, conda-forge
          
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
          
      - name: install pip dependencies
        run: yes | pip3 install -r requirements.txt
        
      - name: install python package
        run: yes | pip3 install .
