name: Python/Database CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      NEO4J_SHA256: 6d9bb8e21a4b80f8edefff89d6fe592812ae26eaf105cbc967bce88b62290bfd
      NEO4J_TARBALL: neo4j-community-4.2.5-unix.tar.gz
      NEO4J_EDITION: community
      NEO4J_HOME: /var/lib/neo4j

    steps:
      - uses: actions/checkout@v2
      
      - name: Install prereqs
        run: |
          sudo apt update
          sudo apt install -y curl wget gosu jq
        # pick up here from https://github.com/neo4j/docker-neo4j-publish/blob/d22293f2e465b63ee5a63f0a2b8f817717a64a8b/4.2.5/community/Dockerfile
      
      - name: Set up conda with Python 3.7.5
        uses: s-weigand/setup-conda@v1.0.5
        with:
          activate-conda: true
          python-version: 3.7.5
          conda-channels: anaconda, conda-forge
          
      - name: install python package
        run: yes | pip3 install .
