name: React build

on:
    - push
    - workflow_dispatch
    - pull_request

jobs:
    build-docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build React App
              working-directory: ./web/packages/app
              run: |
                  npm install
                  npm run build
